#!/bin/sh
# rofi prompt to easily search for a man page to open

exec $TERMINAL -name rofiman -e man "$(apropos --long "$1" | rofi -dmenu -i -l 10 -p apropos | awk '{print $2 $1}' | sed 's/([0-9])//')"
