#!/bin/sh

i3lock \
  --nofork \
  --clock \
  --time-color=ffffffff \
  --date-color=ffffffff \
  --color=000000ff \
  --show-failed-attempts \
  --ignore-empty-password \
  --wrong-text="Denied!" \
  --noinput-text="No Input." \
  --verif-text="Verifying..."

