#!/bin/sh

i3lock \
  --nofork \
  --clock \
  --timecolor=ffffffff \
  --datecolor=ffffffff \
  --color=000000 \
  --show-failed-attempts \
  --ignore-empty-password \
  --wrongtext="Denied!" \
  --noinputtext="No Input." \
  --veriftext="Verifying..."

