#!/usr/bin/env bash

set -euo pipefail

tempdir=$(mktemp -d /tmp/tmp.nix-updateinfo.XXX)
git clone --reference /etc/nixos /etc/nixos $tempdir >/dev/null 2>&1
cd $tempdir

# Update the `nixpkgs` input if flake.lock is older than 7 days
if [ -f /etc/nixos/flake.lock ] && find /etc/nixos/flake.lock -mtime +7 | grep -q .; then
    nix flake lock --update-input nixpkgs
fi

nix build ".#nixosConfigurations.$(hostname).config.system.build.toplevel"
nix store diff-closures /run/current-system ./result \
	| awk '/[0-9] →|→ [0-9]/ && !/nixos/' || echo
cd ~-
rm -rf "$tempdir"

