#!/bin/sh

if [ "$1" == "open" ]; then
  $TERMINAL --title polybar-float -e sudo emerge -auDNv --with-bdeps y @world
fi

RELEASE=$(awk -F= '$1=="ID" { print $2 ;}' /etc/os-release)

if [ "$RELEASE" == "gentoo" ]; then
  COUNT=$(emerge -puDNv --with-bdeps y @world 2> /dev/null | grep "Total" | awk '{split($0,pkginfo," "); print pkginfo[2]}')
else
  COUNT=$(pacman -Qu | wc -l)
fi

# if count is a number display it or an error
if [[ "$COUNT" =~ ^[0-9]+$ ]]; then
  # if count is greater than 0 color it red; otherwise green
  if [ "$COUNT" -gt 0 ]; then
    echo "Updates: %{F#ed0b0b}$COUNT"
  else
    echo "Updates: %{F#00ff00}$COUNT"
  fi
  exit 0
fi

echo "Updates: %{F#ed0b0b}Error"
exit 1

