#!/bin/sh

emerge -puDNv --with-bdeps y @system @world 2> /dev/null 2> /dev/null 2> /dev/null 2> /dev/null 2> /dev/null 2> /dev/null 2> /dev/null 2> /dev/null | grep "Total" | awk '{split($0,pkginfo," "); print pkginfo[2]}'
