#!/bin/sh

if [ "$1" == "open" ]; then
  $TERMINAL --title polybar-float -e sudo emerge -auDNv --with-bdeps y @system @world
fi

COUNT=$(emerge -puDNv --with-bdeps y @system @world 2> /dev/null | grep "Total" | awk '{split($0,pkginfo," "); print pkginfo[2]}')

if [ "$COUNT" -gt 0 ]; then
  echo "%{F#ed0b0b}$COUNT"
else
  echo "%{F#00ff00}$COUNT"
fi
